import { CartProvider } from "@/Components/ContextApi";
import "../styles/main.scss";
import { Inter } from "next/font/google";
import SideBar from "@/Components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <CartProvider>
          <div className="flex w-full">
            <div className="w-[50%]">
              <SideBar />
            </div>
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
